#!/bin/bash

FILE=""
USER_INPUT=""
SIGNING_KEY_ID="86DF67EE"
HELP_MESSAGE="Usage: sign [-k key_id] [-f filename] or provide text input after the command"

# Parse options
while getopts "f:k:" opt; do
  case $opt in
    f) FILE="$OPTARG" ;;
    k) SIGNING_KEY_ID="$OPTARG" ;;  # Overwrite SIGNING_KEY_ID if -k is provided
    *) echo $HELP_MESSAGE; exit 1 ;;
  esac
done

shift $((OPTIND - 1))

# Capture additional user input
if [ -n "$1" ]; then
  USER_INPUT="$*"
fi

# Perform signing based on input
if [ -z "$FILE" ] && [ -n "$USER_INPUT" ]; then
  echo "$USER_INPUT" | gpg --clearsign -a --output "-" --local-user $SIGNING_KEY_ID
elif [ -n "$FILE" ]; then
  gpg --clearsign -a --output "-" --local-user $SIGNING_KEY_ID "$FILE"
else
  echo $HELP_MESSAGE
  exit 1
fi

